/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Role;

import Business.Organizations.Organization;
import Business.SendEmail.SendEmail;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.net.URL;
import javax.swing.JPanel;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ksiec
 */
public class CrisisEmployeePoliceJPanel extends javax.swing.JPanel {

    private UserAccount userAccount;
    private JPanel userProcessContainer;
    private Organization organization;
    private SendEmail sendEmail;
    
    /**
     * Creates new form CrisisEmployeePoliceJPanel
     */
    public CrisisEmployeePoliceJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        crisisEmpWelcomeTxt.setText("Welcome " + userAccount.getEmployee().getName() + "!");
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crisisEmpSearchTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        acceptBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        crisisPoliceEmployeeTbl = new javax.swing.JTable();
        crisisEmpSearchBtn1 = new javax.swing.JButton();
        crisisEmpClearBtn = new javax.swing.JButton();
        crisisEmpWelcomeTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewMapBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(174, 209, 245));
        setMinimumSize(new java.awt.Dimension(1050, 850));
        setPreferredSize(new java.awt.Dimension(1050, 850));

        crisisEmpSearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crisisEmpSearchTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Search Bar:");

        acceptBtn.setText("Accept Request");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        processBtn.setText("Process Request");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        crisisPoliceEmployeeTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Priority Level", "Request Date", "Status", "Student Name", "Emergency Type", "Location", "Comments", "Completed Date"
            }
        ));
        jScrollPane2.setViewportView(crisisPoliceEmployeeTbl);

        jScrollPane1.setViewportView(jScrollPane2);

        crisisEmpSearchBtn1.setText("Search");
        crisisEmpSearchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crisisEmpSearchBtn1ActionPerformed(evt);
            }
        });

        crisisEmpClearBtn.setText("Clear Search");
        crisisEmpClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crisisEmpClearBtnActionPerformed(evt);
            }
        });

        crisisEmpWelcomeTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        crisisEmpWelcomeTxt.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Police Officer Work Area");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/PoliceImage.png"))); // NOI18N

        viewMapBtn.setText("View Location on Map");
        viewMapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMapBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewMapBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(crisisEmpSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)
                                .addComponent(crisisEmpSearchBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(crisisEmpClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(crisisEmpWelcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crisisEmpWelcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crisisEmpSearchBtn1)
                    .addComponent(crisisEmpClearBtn)
                    .addComponent(jLabel4)
                    .addComponent(crisisEmpSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptBtn)
                    .addComponent(processBtn)
                    .addComponent(viewMapBtn))
                .addGap(189, 189, 189))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crisisEmpSearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crisisEmpSearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crisisEmpSearchTxtActionPerformed

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed

        int selectedRow = crisisPoliceEmployeeTbl.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }

        else if (crisisPoliceEmployeeTbl.getValueAt(selectedRow, 2).equals("Completed")) {

            JOptionPane.showMessageDialog(this, "Request has already been completed.");
        }

        else if (crisisPoliceEmployeeTbl.getValueAt(selectedRow, 2).equals("In Progress")) {
            JOptionPane.showMessageDialog(this, "Request is already in progress.");
        }

        else if (crisisPoliceEmployeeTbl.getValueAt(selectedRow, 2).equals("Canceled")) {
            JOptionPane.showMessageDialog(this, "Request was canceled, please make a new selection.");
        }

        else if (crisisPoliceEmployeeTbl.getValueAt(selectedRow, 2).equals("Assigned")) {
            EmergencyRequest emergencyRequest = (EmergencyRequest) userAccount.getWorkQueue().getWorkQueueList().get(selectedRow);
            emergencyRequest.setStatus("In Progress");
        }

        populateTable();
        
    }//GEN-LAST:event_acceptBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        int selectedRow = crisisPoliceEmployeeTbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }

        if (crisisPoliceEmployeeTbl.getValueAt(selectedRow, 2).equals("Canceled")) {
            JOptionPane.showMessageDialog(this, "Request was canceled, please make a new selection.");

        } else if (crisisPoliceEmployeeTbl.getValueAt(selectedRow, 2).equals("Completed")) {
            JOptionPane.showMessageDialog(this, "Request has already been completed.");

        } else if (crisisPoliceEmployeeTbl.getValueAt(selectedRow, 2).equals("Assigned")){
            JOptionPane.showMessageDialog(this, "Please accept request before processing.");

        } else if (crisisPoliceEmployeeTbl.getValueAt(selectedRow, 2).equals("In Progress")) {
            int dialogInput = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Request complete? ", "Complete Request", dialogInput);
            if (dialogResult == 0) {

                WorkQueue workQueue = userAccount.getWorkQueue();
                EmergencyRequest emergencyRequest  = (EmergencyRequest) workQueue.getWorkQueueList().get(selectedRow);
                emergencyRequest.setStatus("Completed");
                emergencyRequest.setDateResolved(new Date());

                Student student1 = emergencyRequest.getSender().getStudent();

                SendEmail.sendEmail(emergencyRequest.getSender().getStudent().getEmail(), student1);
                
                JOptionPane.showMessageDialog(this, "Request completed. Confirmation sent to Student.");

                populateTable();
            }
        }
    }//GEN-LAST:event_processBtnActionPerformed

    private void crisisEmpSearchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crisisEmpSearchBtn1ActionPerformed
        String s = crisisEmpSearchTxt.getText();
        newCrisisEmpFilter(s);
    }//GEN-LAST:event_crisisEmpSearchBtn1ActionPerformed

    private void crisisEmpClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crisisEmpClearBtnActionPerformed
        String s = ("");
        newCrisisEmpFilter(s);
        crisisEmpSearchTxt.setText("");
    }//GEN-LAST:event_crisisEmpClearBtnActionPerformed

    private void viewMapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMapBtnActionPerformed
        int selectedRowIndex = crisisPoliceEmployeeTbl.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view location.");
            return;
        }

        else try{
            Desktop.getDesktop().browse(new URL("http://maps.google.com").toURI());
        } catch (Exception e){}

        DefaultTableModel model = (DefaultTableModel) crisisPoliceEmployeeTbl.getModel();
        EmergencyRequest emergencyRequest = (EmergencyRequest) model.getValueAt(selectedRowIndex, 0);
        String locationTxt = emergencyRequest.getLocation();
        StringSelection stringSelection = new StringSelection(locationTxt);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }//GEN-LAST:event_viewMapBtnActionPerformed

    
    
      private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) crisisPoliceEmployeeTbl.getModel();
        model.setRowCount(0);
        
        crisisPoliceEmployeeTbl.setAutoCreateRowSorter(true);
        
        for (WorkRequest request : userAccount.getWorkQueue().getWorkQueueList()) {
            Object[] row = new Object[8];
            row[0] = ((EmergencyRequest) request);
            row[1] = ((EmergencyRequest) request).getDateOfRequest();
            row[2] = ((EmergencyRequest) request).getStatus();
            row[3] = ((EmergencyRequest) request).getSender().getStudent().getName();
            row[4] = ((EmergencyRequest) request).getEmergencyType();
            row[5] = ((EmergencyRequest) request).getLocation();
            row[6] = ((EmergencyRequest) request).getComments();
            if(request.getStatus().equals("Completed")){
            row[7] = ((EmergencyRequest) request).getDateResolved();
            }
            else{
            row[7] = ""; 
            }
            
            model.addRow(row);
    }
    }
    
    
    public void newCrisisEmpFilter(String s) {
        DefaultTableModel model = (DefaultTableModel) crisisPoliceEmployeeTbl.getModel();
        TableRowSorter<DefaultTableModel> t = new TableRowSorter<DefaultTableModel>(model);
        crisisPoliceEmployeeTbl.setRowSorter(t);
        t.setRowFilter(RowFilter.regexFilter(s));

    }

    public SendEmail getSendEmail() {
        return sendEmail;
    }

    public void setSendEmail(SendEmail sendEmail) {
        this.sendEmail = sendEmail;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton crisisEmpClearBtn;
    private javax.swing.JButton crisisEmpSearchBtn1;
    private javax.swing.JTextField crisisEmpSearchTxt;
    private javax.swing.JLabel crisisEmpWelcomeTxt;
    private javax.swing.JTable crisisPoliceEmployeeTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton processBtn;
    private javax.swing.JButton viewMapBtn;
    // End of variables declaration//GEN-END:variables
}
