/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Role;

import Business.Organizations.Organization;
import Business.SendEmail.SendEmail;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HousingRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.net.URL;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ksiec
 */
public class HousingEmployeeJPanel extends javax.swing.JPanel {

    private UserAccount userAccount;
    private JPanel userProcessContainer;
    private Organization organization;
    private SendEmail sendEmail;

    /**
     * Creates new form HousingEmployeePanel
     *
     * @param userProcessContainer
     * @param userAccount
     * @param organization
     */
    public HousingEmployeeJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        housingEmpWelcomeTxt.setText("Welcome " + userAccount.getEmployee().getName() + "!");
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        housingEmployeeTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acceptBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        housingEmpSearchTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        housingEmpSearchBtn1 = new javax.swing.JButton();
        housingEmpClearBtn = new javax.swing.JButton();
        housingEmpWelcomeTxt = new javax.swing.JLabel();
        viewMapBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 196, 196));
        setMinimumSize(new java.awt.Dimension(1050, 850));
        setPreferredSize(new java.awt.Dimension(1050, 850));

        housingEmployeeTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Priority Level", "Request Date", "Status", "Student Name", "Comments", "Max Price", "Desired Location", "Completed Date"
            }
        ));
        jScrollPane2.setViewportView(housingEmployeeTbl);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Housing Employee Work Area");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/HousingImage.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        acceptBtn.setText("Accept Request");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        processBtn.setText("Process Request");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        housingEmpSearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housingEmpSearchTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Search Bar:");

        housingEmpSearchBtn1.setText("Search");
        housingEmpSearchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housingEmpSearchBtn1ActionPerformed(evt);
            }
        });

        housingEmpClearBtn.setText("Clear Search");
        housingEmpClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housingEmpClearBtnActionPerformed(evt);
            }
        });

        housingEmpWelcomeTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        viewMapBtn.setText("View Location on Map");
        viewMapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMapBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewMapBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(housingEmpSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(housingEmpWelcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(housingEmpSearchBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(housingEmpClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63))))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(housingEmpWelcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housingEmpSearchBtn1)
                    .addComponent(housingEmpClearBtn)
                    .addComponent(jLabel3)
                    .addComponent(housingEmpSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptBtn)
                    .addComponent(processBtn)
                    .addComponent(viewMapBtn))
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed

        int selectedRow = housingEmployeeTbl.getSelectedRow();
        

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row.");
            return;
        } else if (housingEmployeeTbl.getValueAt(selectedRow, 2).equals("Completed")){
            JOptionPane.showMessageDialog(this, "Request has already been completed.");
            
        } else if (housingEmployeeTbl.getValueAt(selectedRow, 2).equals("In Progress")) {
            JOptionPane.showMessageDialog(this, "Request is already in progress.");
            
        } else if (housingEmployeeTbl.getValueAt(selectedRow, 2).equals("Canceled")) {
            JOptionPane.showMessageDialog(this, "Request was canceled, please make a new selection.");
            
        } else if (housingEmployeeTbl.getValueAt(selectedRow, 2).equals("Assigned")) {
            HousingRequest housingRequest = (HousingRequest) userAccount.getWorkQueue().getWorkQueueList().get(selectedRow);
            housingRequest.setStatus("In Progress");
            JOptionPane.showMessageDialog(this, "Request is now in progress.");
            
        }

        populateTable();
        

    }//GEN-LAST:event_acceptBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        int selectedRow = housingEmployeeTbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }

        if (housingEmployeeTbl.getValueAt(selectedRow, 2).equals("Canceled")) {
            JOptionPane.showMessageDialog(this, "Request was canceled, please make a new selection.");

        } else if (housingEmployeeTbl.getValueAt(selectedRow, 2).equals("Completed")) {
            JOptionPane.showMessageDialog(this, "Request has already been completed.");

        } else if (housingEmployeeTbl.getValueAt(selectedRow, 2).equals("Assigned")) {
            JOptionPane.showMessageDialog(this, "Please accept request before processing.");

        } else if (housingEmployeeTbl.getValueAt(selectedRow, 2).equals("In Progress")) {
            int dialogInput = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Request complete? ", "Complete Request", dialogInput);
            if (dialogResult == 0) {

                WorkQueue workQueue = userAccount.getWorkQueue();
                HousingRequest housingRequest = (HousingRequest) workQueue.getWorkQueueList().get(selectedRow);
                housingRequest.setStatus("Completed");
                housingRequest.setDateResolved(new Date());
                
                Student student1 = housingRequest.getSender().getStudent();

                SendEmail.sendEmail(housingRequest.getSender().getStudent().getEmail(), student1);

                JOptionPane.showMessageDialog(this, "Request completed. Confirmation sent to Student.");

                populateTable();
            }
        }

    }//GEN-LAST:event_processBtnActionPerformed

    private void housingEmpSearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housingEmpSearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_housingEmpSearchTxtActionPerformed

    private void housingEmpSearchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housingEmpSearchBtn1ActionPerformed
        String s = housingEmpSearchTxt.getText();
        newHousingEmpFilter(s);
    }//GEN-LAST:event_housingEmpSearchBtn1ActionPerformed

    private void housingEmpClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housingEmpClearBtnActionPerformed
        String s = ("");
        newHousingEmpFilter(s);
        housingEmpSearchTxt.setText("");
    }//GEN-LAST:event_housingEmpClearBtnActionPerformed

    private void viewMapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMapBtnActionPerformed
        int selectedRowIndex = housingEmployeeTbl.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view location.");
            return;
        }
        
        else try{
            Desktop.getDesktop().browse(new URL("http://maps.google.com").toURI());
        } catch (Exception e){}
      
      DefaultTableModel model = (DefaultTableModel) housingEmployeeTbl.getModel();
      HousingRequest housingRequest = (HousingRequest) model.getValueAt(selectedRowIndex, 0);
      String locationTxt = housingRequest.getDesiredLocation();
      StringSelection stringSelection = new StringSelection(locationTxt);
      Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
      clipboard.setContents(stringSelection, null);
      
    }//GEN-LAST:event_viewMapBtnActionPerformed

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) housingEmployeeTbl.getModel();
        model.setRowCount(0);

        housingEmployeeTbl.setAutoCreateRowSorter(true);

        for (WorkRequest request : userAccount.getWorkQueue().getWorkQueueList()) {
            Object[] row = new Object[8];
            row[0] = ((HousingRequest) request);
            row[1] = ((HousingRequest) request).getDateOfRequest();
            row[2] = ((HousingRequest) request).getStatus();
            row[3] = ((HousingRequest) request).getSender().getStudent().getName();
            row[4] = ((HousingRequest) request).getComments();
            row[5] = ((HousingRequest) request).getMaxPrice();
            row[6] = ((HousingRequest) request).getDesiredLocation();
            if (request.getStatus().equals("Completed")) {
                row[7] = ((HousingRequest) request).getDateResolved();
            } else {
                row[7] = "";
            }

            model.addRow(row);
        }
    }

    public void newHousingEmpFilter(String s) {
        DefaultTableModel model = (DefaultTableModel) housingEmployeeTbl.getModel();
        TableRowSorter<DefaultTableModel> t = new TableRowSorter<DefaultTableModel>(model);
        housingEmployeeTbl.setRowSorter(t);
        t.setRowFilter(RowFilter.regexFilter(s));

    }

    public SendEmail getSendEmail() {
        return sendEmail;
    }

    public void setSendEmail(SendEmail sendEmail) {
        this.sendEmail = sendEmail;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton housingEmpClearBtn;
    private javax.swing.JButton housingEmpSearchBtn1;
    private javax.swing.JTextField housingEmpSearchTxt;
    private javax.swing.JLabel housingEmpWelcomeTxt;
    private javax.swing.JTable housingEmployeeTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton processBtn;
    private javax.swing.JButton viewMapBtn;
    // End of variables declaration//GEN-END:variables
}
