/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.EnterpriseAdmin;

import Business.Enterprises.Enterprise;
import Business.Organizations.OrganizationDirectory;
import Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Enterprises.CommunityInvolvementEnterprise;
import Business.Enterprises.CrisisManagementEnterprise;
import Business.Enterprises.Enterprise;
import Business.Enterprises.HousingManagementEnterprise;
import Business.Enterprises.StudentAdvisingEnterprise;
import Business.Enterprises.WellbeingSupportEnterprise;
import Business.Organizations.Organization.orgType;
import Business.Organizations.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author arfinansari
 */
public class AdminManageOrganizationJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private OrganizationDirectory organizationDirectory;
    /**
     * Creates new form AdminManageOrganizationJPanel
     */
    public AdminManageOrganizationJPanel(JPanel userProcessContainer,Enterprise enterprise, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organizationDirectory = organizationDirectory;
        populateTable();
        populateOrganizationComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSelectOrganization = new javax.swing.JLabel();
        cbOrganization = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageOrganization = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(1050, 1050));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Organization");

        lblSelectOrganization.setText("Select an Organization");

        tblManageOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization ID", "Organization"
            }
        ));
        jScrollPane1.setViewportView(tblManageOrganization);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblSelectOrganization)
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbOrganization, 0, 227, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnAdd)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 571, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(cbOrganization.getSelectedItem().equals(Organization.orgType.RealtorOrg.getValue())){
          orgType type = Organization.orgType.RealtorOrg;
          organizationDirectory.createOrg(type);
       }
       else if(cbOrganization.getSelectedItem().equals(Organization.orgType.TherapistOrg.getValue())){
          orgType type = Organization.orgType.TherapistOrg;
          organizationDirectory.createOrg(type);   
       }
       else if(cbOrganization.getSelectedItem().equals(Organization.orgType.HospitalOrg.getValue())){
          orgType type = Organization.orgType.HospitalOrg;
          organizationDirectory.createOrg(type);   
       }
       else if(cbOrganization.getSelectedItem().equals(Organization.orgType.FireDepartmentOrg.getValue())){
          orgType type = Organization.orgType.FireDepartmentOrg;
          organizationDirectory.createOrg(type);   
       }
       
       else if(cbOrganization.getSelectedItem().equals(Organization.orgType.PoliceOrg.getValue())){
          orgType type = Organization.orgType.PoliceOrg;
          organizationDirectory.createOrg(type);   
       }
       
       else if(cbOrganization.getSelectedItem().equals(Organization.orgType.UniversityOrg.getValue())){
          orgType type = Organization.orgType.UniversityOrg;
          organizationDirectory.createOrg(type);   
       }
       
       else if(cbOrganization.getSelectedItem().equals(Organization.orgType.MulticulturalOrg.getValue())){
          orgType type = Organization.orgType.MulticulturalOrg;
          organizationDirectory.createOrg(type);   
       }
        JOptionPane.showMessageDialog(this, "The organization has been added.");
        
        populateTable();
        
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cbOrganization;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectOrganization;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblManageOrganization;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
          DefaultTableModel model = (DefaultTableModel) tblManageOrganization.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : organizationDirectory.getOrgList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrgID();
            row[1] = organization.getOrgName();
            
            model.addRow(row);
        }  
}

private void populateOrganizationComboBox(){
       
       for(Organization.orgType type : Organization.orgType.values()){
           
           if (enterprise instanceof HousingManagementEnterprise){
               cbOrganization.addItem(Organization.orgType.RealtorOrg.getValue());
               break;
           }
           else if(enterprise instanceof CommunityInvolvementEnterprise){
             cbOrganization.addItem(Organization.orgType.MulticulturalOrg.getValue());
             break;
           }
           else if(enterprise instanceof CrisisManagementEnterprise){
              cbOrganization.addItem(Organization.orgType.FireDepartmentOrg.getValue());
              cbOrganization.addItem(Organization.orgType.PoliceOrg.getValue());
              break;
           }
           else if(enterprise instanceof StudentAdvisingEnterprise){
           cbOrganization.addItem(Organization.orgType.UniversityOrg.getValue());
            break;
           }
           else if(enterprise instanceof WellbeingSupportEnterprise){
           cbOrganization.addItem(Organization.orgType.TherapistOrg.getValue());
           cbOrganization.addItem(Organization.orgType.HospitalOrg.getValue());
           break;
           
    }
